name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Give execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: List build/libs
        run: ls -l build/libs/

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: nathylozz54/torneo-sport:latest
          file: Dockerfile
          build-args: |
            JAR_FILE=build/libs/torneo-esports-0.0.1-SNAPSHOT.jar

      - name: Build Docker image
        run: docker build -t nathylozz54/torneo-sport:latest .

      - name: Push Docker image
        run: docker push nathylozz54/torneo-sport:latest
